(() => {
  "use strict";
  const C=window.ChachaNfcCore, host=document.getElementById("view-ndef");
  if(!C||!host)return;
  const $=id=>document.getElementById(id), DRAFT="chachanfc_nfc_draft_v2", BATCH="chachanfc_nfc_batch_v2", BASE="https://laboratorio-evcs.web.app/?nfc=";
  const safe=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
  const status=(el,msg,type="")=>{el.textContent=msg;el.className=`status ${type}`.trim();};
  let pack=C.json(DRAFT,[]), queue=C.json(BATCH,[]);

  const card=document.createElement("article");
  card.className="card nfc-studio-card";
  card.innerHTML=`
    <div class="nfc-studio-title"><div><span class="pill">EvCS • laboratório</span><h2>NFC Studio</h2><p class="muted">Raio-X, gravação avançada, tags dinâmicas, produção em lote e segurança sem misturar com o fluxo operacional.</p></div><div class="nfc-studio-badge">NFC+</div></div>
    <div class="nfc-studio-tabs"><button class="nfc-studio-tab active" data-pane="ray">Raio-X</button><button class="nfc-studio-tab" data-pane="write">Gravar</button><button class="nfc-studio-tab" data-pane="batch">Lote</button><button class="nfc-studio-tab" data-pane="security">Segurança</button><button class="nfc-studio-tab" data-pane="audit">Histórico</button></div>

    <section class="nfc-studio-pane active" data-panel="ray">
      <div class="nfc-studio-callout"><strong>Raio-X da tag</strong><span>UID, registros, bytes NDEF, fingerprint SHA-256 e interpretação EVCS. O Web NFC não informa modelo físico nem capacidade total do chip.</span></div>
      <button class="btn block" id="labRayRead">Ler tag e analisar</button><div class="status" id="labRayStatus">Aguardando leitura.</div><div id="labRayMeta" class="nfc-lab-meta-grid" hidden></div><div id="labRayWarn"></div><div id="labRayRecords" class="nfc-record-list"></div>
    </section>

    <section class="nfc-studio-pane" data-panel="write">
      <div class="nfc-studio-callout"><strong>Compositor de registros</strong><span>Adicione vários itens, reordene e grave juntos. “EvCS dinâmico” cria metadados EVCS2 + URL baseada em token curto.</span></div>
      <div class="grid two nfc-compose-grid"><div><div class="field"><label for="labType">Adicionar</label><select id="labType"><option value="text">Texto</option><option value="link">Link</option><option value="email">E-mail</option><option value="phone">Telefone</option><option value="sms">SMS</option><option value="geo">Geolocalização</option><option value="wifi">Wi-Fi</option><option value="app">Aplicativo / deep link</option><option value="contact">Contato / vCard</option><option value="json">JSON</option><option value="evcs">EvCS dinâmico</option></select></div><div id="labFields"></div><button class="btn secondary block" id="labAdd">+ Adicionar ao pacote</button></div>
      <div><div class="nfc-package-head"><div><strong>Pacote</strong><div class="muted small" id="labPackStats"></div></div><button class="btn ghost" id="labPackClear">Limpar</button></div><div id="labPack" class="nfc-record-list compact"></div></div></div>
      <div class="nfc-write-options"><div class="field"><label for="labWriteMode">Ao gravar</label><select id="labWriteMode"><option value="replace">Substituir pelos registros preparados</option><option value="append">Preservar atuais e acrescentar</option></select></div><div class="actions"><button class="btn ghost" id="labImport">Carregar tag no editor</button><button class="btn good" id="labWrite">Gravar + verificar</button></div></div><div class="status" id="labWriteStatus">Nenhuma gravação iniciada.</div>
    </section>

    <section class="nfc-studio-pane" data-panel="batch">
      <div class="nfc-studio-callout"><strong>Produção em lote</strong><span>Uma linha por tag no formato <code>tipo;referência;rótulo</code>. Ex.: <code>funcionario;1548;João Silva</code>.</span></div>
      <div class="field"><label for="labBatchText">Fila</label><textarea id="labBatchText" rows="5" placeholder="funcionario;1548;João Silva&#10;equipamento;PR-01;Prensa 01"></textarea></div>
      <div class="field"><label for="labBatchBase">URL base dinâmica</label><input id="labBatchBase" value="${BASE}"></div><label class="nfc-check-option"><input id="labBatchBackup" type="checkbox" checked> Criar backup antes de cada gravação</label>
      <div class="actions" style="margin-top:10px"><button class="btn secondary" id="labBatchLoad">Carregar fila</button><button class="btn ghost" id="labBatchReset">Limpar fila</button></div><div id="labBatchProgress" class="nfc-batch-progress"></div><div id="labBatchCurrent" class="nfc-batch-current"></div><div class="actions"><button class="btn ghost" id="labBatchSkip">Pular</button><button class="btn good" id="labBatchWrite">Gravar próximo</button></div><div class="status" id="labBatchStatus">Carregue uma fila para iniciar.</div>
    </section>

    <section class="nfc-studio-pane" data-panel="security">
      <div class="nfc-studio-callout warn"><strong>Segurança e recuperação</strong><span>Senha de chip, setores MIFARE e contador NTAG exigem acesso nativo e ficam fora do Web NFC. Aqui ficam as operações NDEF suportadas.</span></div>
      <div class="nfc-security-actions"><div class="nfc-action-card"><strong>Último backup</strong><span class="muted small" id="labBackupInfo"></span><button class="btn secondary block" id="labRestore">Restaurar</button></div><div class="nfc-action-card"><strong>Limpar NDEF</strong><span class="muted small">Cria backup e substitui a mensagem por um registro vazio.</span><button class="btn danger block" id="labClearTag">Limpar conteúdo</button></div><div class="nfc-action-card danger-zone"><strong>Somente leitura</strong><span class="muted small">Pode ser irreversível quando a tag suporta.</span><button class="btn danger block" id="labReadOnly">Bloquear gravação</button></div></div><div class="status" id="labSecurityStatus">Nenhuma ação executada.</div>
    </section>

    <section class="nfc-studio-pane" data-panel="audit">
      <div class="nfc-studio-callout"><strong>Auditoria local</strong><span>Histórico deste aparelho para comparar UID, token e fingerprint. No EvCS final, isso deve migrar para auditoria central.</span></div><div class="actions"><button class="btn secondary" id="labAuditExport">Exportar JSON</button><button class="btn ghost" id="labAuditClear">Limpar histórico</button></div><div id="labAudit" class="nfc-audit-list"></div>
    </section>`;
  host.insertBefore(card,host.firstChild);

  card.querySelectorAll(".nfc-studio-tab").forEach(b=>b.addEventListener("click",()=>{card.querySelectorAll(".nfc-studio-tab").forEach(x=>x.classList.toggle("active",x===b));card.querySelectorAll(".nfc-studio-pane").forEach(x=>x.classList.toggle("active",x.dataset.panel===b.dataset.pane));if(b.dataset.pane==="audit")renderAudit();if(b.dataset.pane==="security")backupInfo();if(b.dataset.pane==="batch")renderBatch();}));

  const defs={
    text:[["text","Texto","textarea"]], link:[["url","URL","url"]],
    email:[["email","E-mail","email"],["subject","Assunto","text"],["body","Mensagem","textarea"]], phone:[["phone","Telefone","tel"]], sms:[["phone","Telefone","tel"],["body","Mensagem","textarea"]],
    geo:[["lat","Latitude","text"],["lng","Longitude","text"],["label","Rótulo","text"]], wifi:[["ssid","Rede / SSID","text"],["password","Senha Wi-Fi","text"],["security","Segurança","select",[["WPA","WPA/WPA2"],["WEP","WEP"],["nopass","Sem senha"]]]],
    app:[["url","Deep link / URI","text"]], contact:[["name","Nome","text"],["phone","Telefone","tel"],["email","E-mail","email"],["company","Empresa","text"]], json:[["json","JSON","textarea"]],
    evcs:[["entity","Entidade EvCS","select",[["funcionario","Funcionário"],["equipamento","Equipamento"],["veiculo","Veículo"],["ferramenta","Ferramenta"],["amostra","Amostra"],["corpo_prova","Corpo de prova"],["documento","Documento"],["treinamento","Treinamento"],["inspecao","Inspeção / FVS"],["ponto","Ponto / local"],["emergencia","Emergência"]]],["ref","ID / referência","text"],["label","Rótulo","text"],["token","Token (opcional)","text"],["base","URL base","text"]]
  };
  function fields(){const t=$("labType").value,box=$("labFields");box.innerHTML="";(defs[t]||[]).forEach(([name,label,type,opts])=>{const d=document.createElement("div");d.className="field";const l=document.createElement("label");l.textContent=label;let i;if(type==="textarea"){i=document.createElement("textarea");i.rows=3;}else if(type==="select"){i=document.createElement("select");opts.forEach(([v,s])=>i.add(new Option(s,v)));}else{i=document.createElement("input");i.type=type;}i.dataset.f=name;if(name==="base")i.value=BASE;d.append(l,i);box.append(d);});if(t==="evcs"){const n=document.createElement("div");n.className="status info";n.textContent="Protótipo: o token curto permite alterar o destino no EvCS sem regravar a tag quando o resolvedor estiver implementado.";box.append(n);}}
  const vals=()=>Object.fromEntries([...$("labFields").querySelectorAll("[data-f]")].map(i=>[i.dataset.f,i.value.trim()]));
  const req=(v,n)=>{if(!v)throw new Error(`Preencha “${n}”.`);return v;};
  function build(type,v){
    if(type==="text")return[C.textRecord(req(v.text,"Texto"),"Texto")];
    if(type==="link")return[C.urlRecord(new URL(req(v.url,"URL")).href,"Link")];
    if(type==="email"){const q=new URLSearchParams();if(v.subject)q.set("subject",v.subject);if(v.body)q.set("body",v.body);return[C.urlRecord(`mailto:${req(v.email,"E-mail")}${q.toString()?`?${q}`:""}`,`E-mail · ${v.email}`)];}
    if(type==="phone")return[C.urlRecord(`tel:${req(v.phone,"Telefone").replace(/\s+/g,"")}`,`Telefone · ${v.phone}`)];
    if(type==="sms")return[C.urlRecord(`sms:${req(v.phone,"Telefone").replace(/\s+/g,"")}${v.body?`?body=${encodeURIComponent(v.body)}`:""}`,`SMS · ${v.phone}`)];
    if(type==="geo")return[C.urlRecord(`geo:${req(v.lat,"Latitude")},${req(v.lng,"Longitude")}${v.label?`?q=${encodeURIComponent(`${v.lat},${v.lng}(${v.label})`)}`:""}`,`Localização · ${v.label||v.lat}`)];
    if(type==="wifi"){const e=x=>(x||"").replace(/[;,:\\]/g,m=>`\\${m}`);return[C.textRecord(`WIFI:T:${v.security||"WPA"};S:${e(req(v.ssid,"SSID"))};P:${e(v.password)};;`,`Wi-Fi · ${v.ssid}`,"wifi")];}
    if(type==="app")return[C.urlRecord(req(v.url,"Deep link / URI"),"Aplicativo / deep link")];
    if(type==="contact"){const x=["BEGIN:VCARD","VERSION:3.0",`FN:${req(v.name,"Nome")}`];if(v.phone)x.push(`TEL:${v.phone}`);if(v.email)x.push(`EMAIL:${v.email}`);if(v.company)x.push(`ORG:${v.company}`);x.push("END:VCARD");return[C.item({recordType:"mime",mediaType:"text/vcard",data:x.join("\r\n")},{title:`Contato · ${v.name}`,preview:v.phone||v.email||v.name,kind:"contact"})];}
    if(type==="json"){const x=JSON.stringify(JSON.parse(req(v.json,"JSON")));return[C.item({recordType:"mime",mediaType:"application/json",data:x},{title:"JSON",preview:x,kind:"json"})];}
    if(type==="evcs"){const p=C.evcsPackage({entity:req(v.entity,"Entidade"),ref:req(v.ref,"ID / referência"),label:v.label||v.ref,token:v.token,base:v.base||BASE});return p.records;}
    throw new Error("Tipo não suportado.");
  }
  function renderPack(){const box=$("labPack");box.innerHTML="";if(!pack.length)box.innerHTML='<div class="empty nfc-empty-small">Nenhum registro preparado.</div>';pack.forEach((x,i)=>{const r=document.createElement("div");r.className="nfc-record-item compact";r.innerHTML=`<div class="nfc-record-index">${i+1}</div><div class="nfc-record-main"><strong></strong><span class="muted small"></span><div class="nfc-record-tags"><span>${safe(x.recordType)}</span>${x.mediaType?`<span>${safe(x.mediaType)}</span>`:""}</div></div><div class="nfc-record-actions"><button data-a="up" data-i="${i}">↑</button><button data-a="down" data-i="${i}">↓</button><button data-a="remove" data-i="${i}">×</button></div>`;r.querySelector("strong").textContent=x.title;r.querySelector(".muted").textContent=x.preview||"";box.append(r);});$("labPackStats").textContent=`${pack.length} registro(s) · ${C.dataBytes(pack)} bytes de dados`;$("labWrite").disabled=!pack.length;C.put(DRAFT,pack);}
  $("labType").addEventListener("change",fields);$("labAdd").addEventListener("click",()=>{try{pack.push(...build($("labType").value,vals()));renderPack();if($("labType").value==="evcs")fields();}catch(e){status($("labWriteStatus"),e.message,"bad");}});
  $("labPack").addEventListener("click",e=>{const b=e.target.closest("button[data-a]");if(!b)return;const i=+b.dataset.i,a=b.dataset.a;if(a==="remove")pack.splice(i,1);if(a==="up"&&i>0)[pack[i-1],pack[i]]=[pack[i],pack[i-1]];if(a==="down"&&i<pack.length-1)[pack[i+1],pack[i]]=[pack[i],pack[i+1]];renderPack();});
  $("labPackClear").addEventListener("click",()=>{if(pack.length&&!confirm("Limpar o pacote do editor?"))return;pack=[];renderPack();});
  $("labImport").addEventListener("click",async()=>{const s=$("labWriteStatus");status(s,"Aproxime a tag para importar…","info");try{const e=await C.read();pack=Array.from(e.message.records||[]).map(C.fromRecord);renderPack();status(s,`✅ ${pack.length} registro(s) carregado(s) no editor.`,"good");}catch(e){status(s,C.err(e),"bad");}});
  $("labWrite").addEventListener("click",async()=>{const s=$("labWriteStatus");if(!pack.length)return;if(!(await window.ChachaNfcSecurity?.require?.("gravar o pacote NFC")))return;try{status(s,"Aproxime a tag para backup…","info");const before=await C.read(),old=Array.from(before.message.records||[]).map(C.fromRecord);C.saveBackup(before.serialNumber,old,"studio-write");backupInfo();const expected=$("labWriteMode").value==="append"?[...old,...pack]:[...pack],ev=pack.map(C.parseEvcs).find(Boolean);const r=await C.writeVerify(expected,(m,t)=>status(s,m,t),{uid:before.serialNumber,token:ev?.token||"",summary:"Pacote do NFC Studio"});status(s,`✅ Gravado e verificado · ${r.items.length} registro(s) · ${r.fingerprint.slice(0,12)}…`,"good");}catch(e){status(s,C.err(e),"bad");}});

  async function ray(){const s=$("labRayStatus"),meta=$("labRayMeta"),warn=$("labRayWarn"),list=$("labRayRecords");meta.hidden=true;meta.innerHTML=warn.innerHTML=list.innerHTML="";status(s,"Aproxime a tag…","info");try{const e=await C.read(),items=Array.from(e.message.records||[]).map(C.fromRecord),fp=await C.fingerprint(items),evs=items.map(C.parseEvcs).filter(Boolean),tk=evs.find(x=>x.token)?.token||"";[["UID / serial",e.serialNumber||"não informado"],["Registros",items.length],["Payload",`${C.dataBytes(items)} bytes`],["Fingerprint",fp==="indisponível"?fp:`${fp.slice(0,16)}…`],["EvCS",evs.length?`${evs.length} registro(s)`:"nenhum"],["Hardware","não exposto pelo Web NFC"]].forEach(([a,b])=>{const d=document.createElement("div");d.className="nfc-meta-box";d.innerHTML="<span></span><strong></strong>";d.querySelector("span").textContent=a;d.querySelector("strong").textContent=b;meta.append(d);});meta.hidden=false;if(tk){const other=C.history().find(h=>h.token===tk&&h.uid&&e.serialNumber&&h.uid.toLowerCase()!==e.serialNumber.toLowerCase());if(other){const w=document.createElement("div");w.className="status bad";w.textContent=`⚠️ Token ${tk} já foi visto neste aparelho em outro UID (${other.uid}). Heurística de possível duplicação.`;warn.append(w);}}if(evs.length){const x=document.createElement("div");x.className="status info";x.textContent=evs.map(v=>`${v.version}: ${v.type||"-"} · ref=${v.ref||"-"} · token=${v.token||"-"}`).join(" | ");warn.append(x);}items.forEach((x,i)=>{const r=document.createElement("div");r.className="nfc-record-item";r.innerHTML=`<div class="nfc-record-index">${i+1}</div><div class="nfc-record-main"><strong></strong><span class="muted small"></span><div class="nfc-record-tags"><span>${safe(x.recordType)}</span>${x.mediaType?`<span>${safe(x.mediaType)}</span>`:""}</div></div>`;r.querySelector("strong").textContent=x.title;r.querySelector(".muted").textContent=x.preview;list.append(r);});C.audit("ray-x",{uid:e.serialNumber||"",records:items.length,fingerprint:fp,token:tk,summary:"Raio-X NFC"});status(s,`✅ ${items.length} registro(s) analisado(s).`,"good");}catch(e){status(s,C.err(e),"bad");}}
  $("labRayRead").addEventListener("click",ray);

  const norm=v=>String(v||"").trim().toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/\s+/g,"_");
  const next=()=>queue.findIndex(x=>x.status==="pending"||x.status==="error");
  function renderBatch(){const p=$("labBatchProgress"),cur=$("labBatchCurrent"),total=queue.length,done=queue.filter(x=>x.status==="done").length,skip=queue.filter(x=>x.status==="skipped").length,er=queue.filter(x=>x.status==="error").length,i=next();p.innerHTML=total?`<div><strong>${done}/${total}</strong><span>gravados</span></div><div><strong>${total-done-skip}</strong><span>pendentes</span></div><div><strong>${skip}</strong><span>pulados</span></div><div><strong>${er}</strong><span>erros</span></div>`:"";if(i<0){cur.innerHTML=total?'<div class="status good">✅ Fila concluída.</div>':'<div class="empty nfc-empty-small">Nenhuma fila.</div>';$("labBatchWrite").disabled=$("labBatchSkip").disabled=true;}else{const x=queue[i];cur.innerHTML=`<div class="nfc-current-label">Próximo · ${i+1} de ${total}</div><strong></strong><span class="muted small"></span><div class="nfc-record-tags"><span>${safe(x.entity)}</span><span>token ${safe(x.token)}</span></div>`;cur.querySelector("strong").textContent=x.label;cur.querySelector(".muted").textContent=`Referência: ${x.ref}`;$("labBatchWrite").disabled=$("labBatchSkip").disabled=false;}C.put(BATCH,queue);}
  $("labBatchLoad").addEventListener("click",()=>{try{const lines=$("labBatchText").value.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);if(!lines.length)throw new Error("Informe pelo menos uma linha.");queue=lines.map((line,i)=>{const [entity,ref,...label]=line.split(";");return{id:C.id(),entity:norm(req(entity,`tipo da linha ${i+1}`)),ref:req(ref,`referência da linha ${i+1}`),label:label.join(";").trim()||ref,token:C.token(),status:"pending",uid:"",error:""};});renderBatch();status($("labBatchStatus"),`✅ ${queue.length} item(ns) carregado(s).`,"good");}catch(e){status($("labBatchStatus"),e.message,"bad");}});
  $("labBatchReset").addEventListener("click",()=>{if(queue.length&&!confirm("Limpar a fila local?"))return;queue=[];renderBatch();});$("labBatchSkip").addEventListener("click",()=>{const i=next();if(i<0)return;queue[i].status="skipped";renderBatch();});
  $("labBatchWrite").addEventListener("click",async()=>{const s=$("labBatchStatus"),i=next();if(i<0)return;if(!(await window.ChachaNfcSecurity?.require?.("gravar o próximo crachá do lote")))return;const x=queue[i];try{let uid="";if($("labBatchBackup").checked){status(s,"Aproxime a tag para backup…","info");const e=await C.read(),old=Array.from(e.message.records||[]).map(C.fromRecord);uid=e.serialNumber||"";C.saveBackup(uid,old,"batch");backupInfo();}const p=C.evcsPackage({entity:x.entity,ref:x.ref,label:x.label,token:x.token,base:$("labBatchBase").value.trim()||BASE}),r=await C.writeVerify(p.records,(m,t)=>status(s,`Item ${i+1}/${queue.length}: ${m}`,t),{uid,token:x.token,summary:`Lote: ${x.entity} ${x.ref}`});x.status="done";x.uid=r.event.serialNumber||uid||"";x.error="";renderBatch();status(s,`✅ ${x.label} gravado. Próximo item pronto.`,"good");}catch(e){x.status="error";x.error=C.err(e);renderBatch();status(s,x.error,"bad");}});

  function backupInfo(){const b=C.backup();if(!b){$("labBackupInfo").textContent="Nenhum backup local.";$("labRestore").disabled=true;return;}$("labBackupInfo").textContent=`${b.records?.length||0} registro(s) · UID ${b.uid||"não informado"} · ${b.capturedAt?new Date(b.capturedAt).toLocaleString("pt-BR"):""}`;$("labRestore").disabled=!(b.records?.length);}
  $("labRestore").addEventListener("click",async()=>{const s=$("labSecurityStatus"),b=C.backup();if(!b?.records?.length)return;if(!(await window.ChachaNfcSecurity?.require?.("restaurar o backup")))return;if(!confirm("Restaurar o backup no MESMO crachá?"))return;try{const r=await C.writeVerify(b.records,(m,t)=>status(s,m,t),{uid:b.uid,summary:"Backup restaurado"});status(s,`✅ Backup verificado · ${r.fingerprint.slice(0,12)}…`,"good");}catch(e){status(s,C.err(e),"bad");}});
  $("labClearTag").addEventListener("click",async()=>{const s=$("labSecurityStatus");if(!(await window.ChachaNfcSecurity?.require?.("limpar o NDEF")))return;if(!confirm("Apagar todos os registros NDEF? Será criado backup antes."))return;try{status(s,"Aproxime para backup…","info");const e=await C.read(),old=Array.from(e.message.records||[]).map(C.fromRecord);C.saveBackup(e.serialNumber,old,"clear");backupInfo();status(s,"Backup criado. Encoste novamente para limpar…","info");const w=new NDEFReader();await w.write({records:[{recordType:"empty"}]},{overwrite:true});C.audit("clear-ndef",{uid:e.serialNumber||"",records:old.length,summary:"NDEF limpo"});status(s,"✅ NDEF limpo. Backup salvo.","good");}catch(e){status(s,C.err(e),"bad");}});
  $("labReadOnly").addEventListener("click",async()=>{const s=$("labSecurityStatus");if(!(await window.ChachaNfcSecurity?.require?.("tornar a tag somente leitura")))return;if(prompt("Pode ser IRREVERSÍVEL. Digite BLOQUEAR:")!=="BLOQUEAR")return;try{const n=new NDEFReader();if(typeof n.makeReadOnly!=="function")throw new DOMException("makeReadOnly() indisponível.","NotSupportedError");status(s,"Aproxime para backup final…","info");const e=await C.read(),old=Array.from(e.message.records||[]).map(C.fromRecord);C.saveBackup(e.serialNumber,old,"read-only");backupInfo();status(s,"Backup criado. Encoste novamente a MESMA tag…","info");await n.makeReadOnly();C.audit("make-read-only",{uid:e.serialNumber||"",records:old.length,summary:"Tag somente leitura"});status(s,"✅ Navegador confirmou somente leitura.","good");}catch(e){status(s,C.err(e),"bad");}});

  function renderAudit(){const box=$("labAudit"),h=C.history();box.innerHTML="";if(!h.length){box.innerHTML='<div class="empty nfc-empty-small">Nenhum evento local.</div>';return;}h.slice(0,30).forEach(x=>{const r=document.createElement("div");r.className="nfc-audit-item";r.innerHTML='<div class="nfc-audit-head"><strong></strong><span></span></div><div class="muted small"></div><div class="nfc-record-tags"></div>';r.querySelector("strong").textContent=x.summary||x.action;r.querySelector(".nfc-audit-head span").textContent=x.at?new Date(x.at).toLocaleString("pt-BR"):"";r.querySelector(".muted").textContent=x.uid?`UID ${x.uid}`:"UID não registrado";[x.action,x.token?`token ${x.token}`:"",x.fingerprint?`fp ${String(x.fingerprint).slice(0,10)}…`:""].filter(Boolean).forEach(v=>{const t=document.createElement("span");t.textContent=v;r.querySelector(".nfc-record-tags").append(t);});box.append(r);});}
  $("labAuditExport").addEventListener("click",()=>{const blob=new Blob([JSON.stringify({exportedAt:new Date().toISOString(),events:C.history()},null,2)],{type:"application/json"}),u=URL.createObjectURL(blob),a=document.createElement("a");a.href=u;a.download=`chachanfc-auditoria-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(u);});
  $("labAuditClear").addEventListener("click",async()=>{if(!(await window.ChachaNfcSecurity?.require?.("limpar o histórico NFC")))return;if(!confirm("Limpar histórico local?"))return;localStorage.removeItem(C.AUDIT);renderAudit();});window.addEventListener("chachanfc:nfc-audit",renderAudit);

  fields();renderPack();renderBatch();backupInfo();renderAudit();
})();
